added tasks 3, 4
aloneik/python_lessons pull request #2
Opened 2019-02-08 20:11 UTC by aloneik

2019-02-15 17:52 UTC, tatyanachinyaeva requested changes

2019-02-15 17:52 UTC, tatyanachinyaeva commented on lesson_2/decorators/main.py
> +    print get_time_2(), "\n"
if I call get_time_2 with another format - you code won't work, for example:
get_time_2(format="%Y-%m-%d %H:%M")

2019-02-15 17:52 UTC, tatyanachinyaeva commented on lesson_2/decorators/main.py
> +    phones = [
I got:
```
+91 7895 462130
+91 9195 969878
+91 9875 641230
```
when I run your code, correct format is:
```
+91 78954 62130
+91 91959 69878
+91 98756 41230
```

2019-02-15 17:52 UTC, tatyanachinyaeva commented on lesson_2/decorators/main.py
> +    for index in xrange(len(phones)):
looks too complicated. I'd rather cut last 10 numbers and used them (easiest way) or do something else, but without this ugly loop `for index in xrange(len(phones)`
I see why you're using it, but code in python should be readable, only after that you can think about speed and memory usage

2019-02-15 17:52 UTC, tatyanachinyaeva commented on lesson_2/decorators/main.py
> +    print some_calc(3), "\n"
your code prints 8 and 8, though it should have returned 8 and 27. so for 2 it should cache 8, for 1 - 1, for 3 - 27 etc

2019-02-17 13:30 UTC, aloneik commented
fixed

2019-02-22 12:46 UTC, tatyanachinyaeva requested changes

2019-02-22 12:46 UTC, tatyanachinyaeva commented on lesson_2/decorators/main.py
> +    def wrapped(format="%Y/%m/%d %H:%M"):
ну вообще можно просто было использовать стандартный вариант с *args, **kwargs. Когда пишешь декоратор, хочется чтоб он работал со многими функциями и не факт что у них у всех будет одинаковый интерфейс. переделывать не надо, просто имей в виду, что  *args, **kwargs в данном случае - самое удобное

2019-02-22 12:46 UTC, tatyanachinyaeva commented on lesson_2/decorators/main.py
> +        if not arguments in cached:
стандартный вариант - arguments not in cache, это тоже можешь не переделывать т к работает и так и так, но pep-8 рекомендует использовать not in. на будущее - настрой себе в редакторе проверки на pep-8. будешь потихоньку запоминать что там является хорошим стилем, а что - нет.

2019-02-22 12:46 UTC, tatyanachinyaeva commented on lesson_2/decorators/main.py
> +        arguments = (args, namedtuple("FuncKwArgs", kwargs.keys())(**kwargs))
работает в данном случае, но:
@cache
def w(a=0, b=0):
    return a + b * 2


print w(a=1)
print w(b=1)

печатает 
1
1

подсказка - проблема в нэймдтапле

надо переделать

2019-02-22 14:09 UTC, aloneik commented on lesson_2/decorators/main.py
> +        arguments = (args, namedtuple("FuncKwArgs", kwargs.keys())(**kwargs))
Переделал

2019-02-26 17:06 UTC, tatyanachinyaeva requested changes

2019-02-26 17:06 UTC, tatyanachinyaeva commented on lesson_2/decorators/main.py
> +        arguments = (args, tuple((item for item in kwargs.items())))
tuple(kwargs.items()) вернет тот же результат, но проще.
тут появляется проблема, что kwargs - дикт и порядок ключей мы не знаем.

2019-02-27 16:52 UTC, tatyanachinyaeva approved these changes

2019-02-27 17:08 UTC, merged